name: Build and Deploy
on:
  push:
    branches: [ main ]
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run export
          cp .htaccess out/
      - name: Zip 📦
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r out.zip out
      - name: Publish 🚀
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out.zip
          asset_name: out.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release Build"